### ISSUE TITLE
SQL error when loading network from specific HANA Cloud instances.

### ISSUE THREAD

**Issue by weichwarenentwickler** [SAP/sap-hana-plugin-for-cytoscape#4]
I'm running into the following error when loading a network from a specific HANA Cloud instance:
```
SAP DBTech JDBC: [260]: invalid column name: EDGE_SCHEMA_NAME: line 1 col 174 (at pos 173)
```

The very same scenario works fine a against a different HANA Cloud instance. My analysis showed that the SQL call `SELECT VALUE FROM M_HOST_INFORMATION WHERE KEY='build_branch'` returns an empty string and thus the host is considered to be a HANA On-Prem. Subsequently the SQL for On-prem is sent to the HANA Cloud resulting in the above issue.

**Comment by weichwarenentwickler** [comment]
I have opened PR #3 which addresses this issue with a new setting in the **Connect to Database** dialog that let's you override the automatic detection.

**Comment by mkemeter** [comment]
Can you check, if this change solves the issue for you?
https://github.com/SAP/sap-hana-plugin-for-cytoscape/commit/7f55f788380b5f12ac5b6227d70c2a31fd4febce

**Comment by weichwarenentwickler** [comment]
Indeed this solves the issue. And since your correction is more elegant than mine I will close PR #3 as well.
